
hospitalcost<-read.csv("HospitalCosts.csv")
head(hospitalcost)
summary(hospitalcost)
head(hospitalcost$AGE)
summary(hospitalcost$AGE)
table(hospitalcost$AGE)
hist(hospitalcost$AGE)
hist(hospitalcost$AGE, breaks = 10, col="Orange")
summary(as.factor(hospitalcost$AGE))
max(table(hospitalcost$AGE))
max(summary(as.factor(hospitalcost$AGE)))
which.max(table(hospitalcost$AGE))
age <- aggregate(TOTCHG ~ AGE, data = hospitalcost, sum)
max(age)
t <- table(hospitalcost$APRDRG)
d <- as.data.frame(t)
names(d)[1] = 'DiagnosisGroup'
d
which.max(table(hospitalcost$APRDRG))
which.max(t)
which.max(d)          
res <- aggregate(TOTCHG ~ APRDRG, data = hospitalcost, sum)
res
which.max(res$TOTCHG)
res[which.max(res$TOTCHG),]
table(hospitalcost$RACE)
hospitalcost$RACE <- as.factor(hospitalcost$RACE)
fit <- lm(TOTCHG ~ RACE,data=hospitalcost)
fit
summary(fit)
fit1 <- aov(TOTCHG ~ RACE,data=hospitalcost)
summary(fit1)
hospitalcost <- na.omit(hospitalcost)
table(hospitalcost$FEMALE)
a <- aov(TOTCHG ~ AGE+FEMALE,data=hospitalcost)
summary(a)
b <- lm(TOTCHG ~ AGE+FEMALE,data=hospitalcost)
summary(b)
table(hospitalcost$LOS)
cat <- aov(LOS ~ AGE+FEMALE+RACE,data=hospitalcost)
summary(cat)
cat <- lm(LOS ~ AGE+FEMALE+RACE,data=hospitalcost)
summary(cat)
aov(TOTCHG ~.,data=hospitalcost)
mod <- lm(TOTCHG ~ .,data=hospitalcost)
summary(mod)
